# Generated by Django 5.0.7 on 2024-07-30 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_track'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='track',
        ),
    ]
