# Generated by Django 5.0.7 on 2024-07-31 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_student_track'),
        ('tracks', '0002_track_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='tracks.track'),
        ),
    ]
